version: '3.8'
services:
  db:
    image: postgres:15
    env_file: .env.test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  e2e:
    build: .
    env_file: .env.test
    depends_on:
      db:
        condition: service_healthy
    environment:
      MODE: test
    volumes:
      - ./coverage:/app/coverage
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results
    ports:
      - '3001:3001'
